language: ruby
rvm:
  - 2.2.3
env:
  - DB=mysql
script:
  - RAILS_ENV=test
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
 - cp config/database.yml.travis config/database.yml
 - chmod +x config/database.yml
 - cp config/secrets.yml.template config/secrets.yml
 - chmod +x config/secrets.yml
 - mysql -e 'create database fsek_test'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/48801aad6f679014cfd3
